export enum ReserveringEnum {
  DATUM_OVERSCHREDEN = "DATUM OVERSCHREDEN",
  IN_BEHANDELING = "IN BEHANDELING",
  STAAT_KLAAR = "STAAT KLAAR",
  AFGEROND = "AFGEROND",
  OPGEHAALD = "OPGEHAALD",
  GEANNULEERD = "GEANNULEERD"
}
